"""
Django settings for gon_cal project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
# import logging
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'register.apps.RegisterConfig',
    'mcal.apps.McalConfig',
    'control.apps.ControlConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'gon_cal.middleware.UAmiddleware',
]

ROOT_URLCONF = 'gon_cal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gon_cal.context_processors.version_no',
            ],
        },
    },
]

WSGI_APPLICATION = 'gon_cal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'cal.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# 追加設定
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
# For Django4
CSRF_TRUSTED_ORIGINS = ['https://*.sophiagardens.org']
VERSION_NO = '2023-04-03 開発版'
# Userモデル
AUTH_USER_MODEL = 'register.User'

LOGIN_URL = 'register:login'
LOGIN_REDIRECT_URL = 'mcal:calendar'
LOGOUT_REDIRECT_URL = 'mcal:calendar'

# マークダウンの拡張
MARKDOWN_EXTENSIONS = [
    'markdown.extensions.extra',
    'markdown.extensions.codehilite',
]

# ブラウザを閉じたらログアウトさせる。
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# secret keyのセット。
try:
    from .private_settings import *
except ImportError:
    pass
# DEBUGモードのセット。
try:
    from .local_settings import *
except ImportError:
    pass

# ログ出力先のディレクトリを設定する
# https://docs.djangoproject.com/ja/4.0/topics/logging/
# https://qiita.com/okoppe8/items/3e8ab77c5801a7d21991
LOG_BASE_DIR = os.path.join("logs", )
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    "formatters": {"simple": {"format": "%(asctime)s [%(levelname)s] %(message)s"}},
    # ログの出力方法についての設定。
    "handlers": {
        # DEBUG = Falseの場合、ログファイルに出力する。
        "info": {
            "level": "INFO",
            "filters": ['require_debug_false'],
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 51200,
            "backupCount": 5,
            "filename": os.path.join(LOG_BASE_DIR, "info.log"),
            "formatter": "simple",
        },
        "warning": {
            "level": "WARNING",
            "filters": ['require_debug_false'],
            "class": "logging.handlers.RotatingFileHandler",
            "maxBytes": 51200,
            "backupCount": 5,
            "filename": os.path.join(LOG_BASE_DIR, "warning.log"),
            "formatter": "simple",
        },
        # DEBUG = Trueの場合、コンソールにログ出力する。
        "debug": {
            "level": "DEBUG",
            "filters": ['require_debug_true'],
            "class": 'logging.StreamHandler',
            "formatter": "simple",
        },
    },
    # ロガーはルートロガーのみとする。
    "root": {
        "handlers": ["info", "warning", "debug"],
        "level": "DEBUG",
    },
}

# For debugging
if DEBUG:
    # 開発環境における静的ファイルの場所を指定する。
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, "static"),
    )
    # # will output to your console
    # logging.basicConfig(
    #     level=logging.DEBUG,
    #     format='%(asctime)s %(levelname)s %(message)s',
    # )
else:
    # for nginx
    STATIC_ROOT = '/code/static'
    # # will output to logging file
    # logging.basicConfig(
    #     level=logging.DEBUG,
    #     format='%(asctime)s %(levelname)s %(message)s',
    #     filename='/my_log_file.log',
    #     filemode='a'
    # )
