# Generated by Django 3.1.3 on 2020-11-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='summary',
        ),
    ]
