# Generated by Django 3.1.4 on 2020-12-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='align',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='left', max_length=8, verbose_name='文字揃え'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='memo',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
    ]
