# Generated by Django 3.1.5 on 2021-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcal', '0002_auto_20201208_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='予定'),
        ),
    ]
