# Generated by Django 3.1.3 on 2020-11-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcal', '0002_auto_20201124_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='created_at',
        ),
    ]
