# Generated by Django 3.1.3 on 2020-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcal', '0003_remove_schedule_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='コメント'),
        ),
    ]
