# Generated by Django 4.0.5 on 2022-08-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp_user_flg', models.BooleanField(default=False, verbose_name='仮登録')),
            ],
        ),
    ]
